checks:
    php:
        code_rating: true
        duplication: true

tools:
    external_code_coverage:
        timeout: 1800
    php_analyzer: true
    php_mess_detector: true
    php_sim: true
    sensiolabs_security_checker: true
    php_changetracking: true
    php_cs_fixer:
          config: { level: psr2 }